### ISSUE TITLE
Implement pre-commit hooks for black, isort, pyupgrade and flake8

### ISSUE THREAD

**Issue by sponsfreixes** [edmondchuc/flask-htmx#18]
@edmondchuc what do you think about adopting black, isort, pyupgrade and flake8 for code formatting and linting?

If they are set up as pre-commit hooks, that would ensure uniformity of code for future contributions.

**Comment by edmondchuc** [comment]
I think they're a good idea. The checks can be triggered on each push in GitHub Actions. We can have pre-commit hooks as well, but they are not enforceable in local dev environments.

**Comment by sponsfreixes** [comment]
Closing as this was implemented some time ago.
