### ISSUE TITLE
I Have Included flask-htmx Into Awesome-Python-HTMX, seeking your feedback

### ISSUE THREAD

**Issue by benjamin-kirkbride** [edmondchuc/flask-htmx#23]
A few of us at PyCon this year got together and brainstormed a new Web Stack that we are calling PyHAT (Python, htmx, ASGI, TailwindCSS). The first thing we set out to do is create an "Awesome" collection of active tools/libraries/projects in that space, including yours!

If you could take a look, and also participate in https://github.com/PyHAT-stack/awesome-python-htmx/discussions/1 that would be greatly appreciated!

**Comment by sponsfreixes** [comment]
This is an excellent initiative! I will personally gladly contribute with helping adding resources or improving the documentation.
