### ISSUE TITLE
Compatibility issue with Flask > 3.0

### ISSUE THREAD

**Issue by WilliamLafarie** [edmondchuc/flask-htmx#28]
Hi! 
It seems that flask-htmx is not compatible with new versions of Flask (>3.0.0)
`flask-htmx 0.3.1 depends on Flask<3.0.0 and >=2.0.2`
Thanks :pray:

**Comment by chrisdellisantirn** [comment]
I removed flask HTMX from my dependencies after upgrading to Flask 3.0. 

If you need to check for incoming HTMX requests in your route you can use this instead:
`if request.headers.get("HX-Request") == "true":`
