### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by zipus** [edmondchuc/flask-htmx#35]
I don't know the criteria timing for releases, but can I ask for a new release?
I'm interested in https://github.com/edmondchuc/flask-htmx/commit/93855a7e14f5422f0472b47975cae77a583d2e3e.
Thanks!

**Comment by edmondchuc** [comment]
Thanks for the nudge! It's available now in 0.4.0.

https://github.com/edmondchuc/flask-htmx/releases/tag/0.4.0
